std = "lua51"
max_line_length = false

exclude_files = {
    "!PatchWerk/**",
    ".release/**",
}

globals = {
    "PatchWerkDB",
    "AddonTweaksDB",
    "SLASH_PATCHWERK1",
    "SLASH_PATCHWERK2",
    "SlashCmdList",
}

read_globals = {
    -- WoW API
    "CreateFrame",
    "UIParent",
    "GameTooltip",
    "DEFAULT_CHAT_FRAME",
    "ReloadUI",
    "InCombatLockdown",
    "GetTime",
    "C_Timer",
    "C_AddOns",
    "hooksecurefunc",
    "tinsert",
    "wipe",
    "pcall",
    "LibStub",
    "UISpecialFrames",
    "InterfaceOptions_AddCategory",
    "InterfaceOptionsFrame_OpenToCategory",
    "Settings",
    "GameFontNormal",
    "GameFontNormalLarge",
    "GameFontNormalHuge",
    "GameFontHighlight",
    "GameFontHighlightSmall",
    "GameFontDisable",
    "GameFontDisableSmall",
    "GetAddOnMetadata",
    "IsAddOnLoaded",

    -- WoW globals used by patches
    "Details",
    "Plater",
    "Pawn",
    "PawnGetCachedItem",
    "PawnUpdateTooltip",
    "PawnIsItemAnUpgrade",
    "TipTac",
    "Questie",
    "QuestieLoader",
    "GBB",
    "Bartender4",
    "OmniCC",
    "Prat",
    "GatherMate2",
    "Quartz3",
    "Auctionator",
    "AuctionatorCancellingFrameMixin",
    "AuctionatorAHThrottlingFrameMixin",
    "Cell",
    "BigDebuffs",
    "EasyFrames",
    "BugSack",
    "BugGrabber",
    "BugGrabberDB",
    "LBIS",
    "NIT",
    "Gargul",
    "MoveAny",
    "Attune",
    "Attune_spairs",
    "AtlasLoot",
    "SexyMap",
    "VUHDO_determineDebuff",
    "VUHDO_updateUnitRange",
    "VUHDO_tryInspectNext",
    "TitanPanelButton_UpdateButton",
}
