name: Bug Report
description: Report a bug or issue with PatchWerk
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: PatchWerk Version
      description: "Type `/pw version` in-game to find this."
      placeholder: "e.g. 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: addon
    attributes:
      label: Affected Addon
      description: Which addon's patch is causing the issue?
      options:
        - AtlasLoot Classic
        - Attune
        - Auctionator
        - AutoLayer
        - Baganator
        - Bartender4
        - BigDebuffs
        - BigWigs
        - BugSack
        - Cell
        - ClassTrainerPlus
        - Details
        - EasyFrames
        - Gargul
        - GatherMate2
        - Leatrix Maps
        - Leatrix Plus
        - LFG Bulletin Board
        - LoonBestInSlot
        - MoveAny
        - NameplateSCT
        - Nova Instance Tracker
        - NovaWorldBuffs
        - OmniCC
        - Pawn
        - Plater
        - Prat-3.0
        - Quartz
        - Questie
        - QuestXP
        - RatingBuster
        - SexyMap
        - TipTac
        - Titan Panel
        - VuhDo
        - Other / General
    validations:
      required: true

  - type: input
    id: addon-version
    attributes:
      label: Target Addon Version
      description: "The version of the affected addon (check its TOC or /pw outdated)."
      placeholder: "e.g. 1.47.9-classic"

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly. What did you expect to happen vs what actually happened?
      placeholder: "When I open the damage meter during combat, the game freezes..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Enable the Details_refreshCap patch
        2. Open Details damage meter
        3. Enter combat
        4. ...

  - type: textarea
    id: errors
    attributes:
      label: Lua Errors
      description: "Paste any Lua errors here. Use BugSack or `/console scriptErrors 1` to see them."
      render: text
